<a href="https://colab.research.google.com/github/praneethreddynaredla-commits/movie-recommendation-system/blob/main/Movie_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import requests
url="https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlOWViOGJmNDZlNzdhMjVhZGY0YTAzZjkzMTM0MDRiYSIsIm5iZiI6MTc4Njc5MzQ1Ny4wNTMsInN1YiI6IjZhODA0ZGYxMDM1N2FiNTY1OTkzZjlmOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.WEJ-oAD2jw066P6gcSoNSf7aPpSOIuQZLrpFV__liN8"
}

response = requests.get(url=url, headers=headers)

print(response)

<Response [200]>

In [103]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg',
   'genre_ids': [16, 28, 12, 14],
   'id': 980431,
   'title': 'Avatar Aang: The Last Airbender',
   'original_language': 'en',
   'original_title': 'Avatar Aang: The Last Airbender',
   'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
   'popularity': 122.7143,
   'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
   'release_date': '2026-07-24',
   'softcore': False,
   'video': False,
   'vote_average': 9.259,
   'vote_count': 848},
  {'adult': False,
   'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
   'genre_ids': [35, 10749],
   'id': 1632181,
   'title': 'Accidental Partners',
   'original_language': 'es',
   'original_title': 'Socias por accidente',
   'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
   'popularity': 24.9711,
   'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
   'release_date': '2026-03-12',
   'softcore': False,
   'video': False,
   'vote_average': 8.905,
   'vote_count': 349},
  {'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 51.2062,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.9,
   'vote_count': 2098},
  {'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 56.9245,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.727,
   'vote_count': 31025},
  {'adult': False,
   'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
   'genre_ids': [16, 28, 14],
   'id': 1311031,
   'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
   'original_language': 'ja',
   'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
   'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
   'popularity': 109.4062,
   'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
   'release_date': '2025-07-18',
   'softcore': False,
   'video': False,
   'vote_average': 8.71,
   'vote_count': 1831},
  {'adult': False,
   'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 59.0628,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.686,
   'vote_count': 23342},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'genre_ids': [10402, 18],
   'id': 936075,
   'title': 'Michael',
   'original_language': 'en',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'popularity': 84.8355,
   'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.7,
   'vote_count': 4003},
  {'adult': False,
   'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 131.1924,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.656,
   'vote_count': 7038},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 31.3571,
   'poster_path': '/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.571,
   'vote_count': 14171},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 34.1502,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.57,
   'vote_count': 17735},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 27.3154,
   'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.568,
   'vote_count': 10229},
  {'adult': False,
   'backdrop_path': '/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg',
   'genre_ids': [18, 10749],
   'id': 1232449,
   'title': 'Young Hearts',
   'original_language': 'nl',
   'original_title': 'Young Hearts',
   'overview': '14-year-old Elias increasingly feels like an outsider in his village. When he meets his new neighbour of the same age, Alexander, Elias is confronted with his burgeoning sexuality.',
   'popularity': 18.1933,
   'poster_path': '/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg',
   'release_date': '2024-10-26',
   'softcore': False,
   'video': False,
   'vote_average': 8.567,
   'vote_count': 304},
  {'adult': False,
   'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 62.3278,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.534,
   'vote_count': 36383},
  {'adult': False,
   'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 35.3381,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.534,
   'vote_count': 18688},
  {'adult': False,
   'backdrop_path': '/fr7F7156W8A5lSvrqHwNjtyrmLG.jpg',
   'genre_ids': [16, 28, 10749, 14],
   'id': 1218925,
   'title': 'Chainsaw Man - The Movie: Reze Arc',
   'original_language': 'ja',
   'original_title': '劇場版 チェンソーマン レゼ篇',
   'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
   'popularity': 34.5511,
   'poster_path': '/crBfxNvvsQV3rATX12EuX4W9ECo.jpg',
   'release_date': '2025-09-19',
   'softcore': False,
   'video': False,
   'vote_average': 8.525,
   'vote_count': 1112},
  {'adult': False,
   'backdrop_path': '/amZavErrjrdgDwhsIdpWxHNenIx.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 34.2412,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.506,
   'vote_count': 19603},
  {'adult': False,
   'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'title': 'Dilwale Dulhania Le Jayenge',
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 14.3904,
   'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
   'release_date': '1995-10-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.505,
   'vote_count': 4612},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 50.4122,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.504,
   'vote_count': 27079},
  {'adult': False,
   'backdrop_path': '/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'title': 'Parasite',
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 37.1941,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'softcore': False,
   'video': False,
   'vote_average': 8.49,
   'vote_count': 21079},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'title': 'Your Name.',
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 27.715,
   'poster_path': '/vfJFJPepRKapMd5G2ro7klIRysq.jpg',
   'release_date': '2016-07-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.484,
   'vote_count': 12842}],
 'total_pages': 556,
 'total_results': 11108}

In [104]:
import pandas as pd

json_data = response.json()
if 'results' in json_data:
    df=pd.DataFrame(json_data['results'])
else:
    print("Warning: 'results' key not found in response. Creating an empty DataFrame for this page.")
    df=pd.DataFrame()

In [105]:
df

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",122.7143,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.259,848
1,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,24.9711,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.905,349
2,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",51.2062,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.900,2098
3,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,56.9245,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.727,31025
4,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,109.4062,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,False,False,8.710,1831
5,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",59.0628,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.686,23342
6,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",84.8355,/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg,2026-04-22,False,False,8.700,4003
7,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,131.1924,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.656,7038
8,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,The Godfather Part II,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,31.3571,/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg,1974-12-20,False,False,8.571,14171
9,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,Schindler's List,en,Schindler's List,The true story of how businessman Oskar Schind...,34.1502,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,False,False,8.570,17735
10,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,12 Angry Men,en,12 Angry Men,The defense and the prosecution have rested an...,27.3154,/ppd84D2i9W8jXmsyInGyihiSyqz.jpg,1957-04-10,False,False,8.568,10229
11,False,/3HaqAPZ0C8n6Hd5T86U53yJlBAN.jpg,"[18, 10749]",1232449,Young Hearts,nl,Young Hearts,14-year-old Elias increasingly feels like an o...,18.1933,/iGCtYxfuvXfy0BD5m6p7vKuPOxS.jpg,2024-10-26,False,False,8.567,304
12,False,/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg,"[28, 80, 53]",155,The Dark Knight,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,62.3278,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,False,False,8.534,36383
13,False,/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg,"[16, 10751, 14]",129,Spirited Away,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",35.3381,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,False,False,8.534,18688
14,False,/fr7F7156W8A5lSvrqHwNjtyrmLG.jpg,"[16, 28, 10749, 14]",1218925,Chainsaw Man - The Movie: Reze Arc,ja,劇場版 チェンソーマン レゼ篇,"In a brutal war between devils, hunters, and s...",34.5511,/crBfxNvvsQV3rATX12EuX4W9ECo.jpg,2025-09-19,False,False,8.525,1112
15,False,/amZavErrjrdgDwhsIdpWxHNenIx.jpg,"[14, 18, 80]",497,The Green Mile,en,The Green Mile,A supernatural tale set on death row in a Sout...,34.2412,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,False,False,8.506,19603
16,False,/84beTJf26mfhoasUlKSOiNSutyS.jpg,"[35, 18, 10749]",19404,Dilwale Dulhania Le Jayenge,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",14.3904,/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg,1995-10-20,False,False,8.505,4612
17,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,The Lord of the Rings: The Return of the King,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,50.4122,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,False,False,8.504,27079
18,False,/vbC0rzdrb7Ohc2TkbEbxtOABECe.jpg,"[35, 53, 18]",496243,Parasite,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",37.1941,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,False,False,8.490,21079
19,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,Your Name.,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,27.7150,/vfJFJPepRKapMd5G2ro7klIRysq.jpg,2016-07-01,False,False,8.484,12842

In [106]:
df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",122.7143,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.259,848
1,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,24.9711,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.905,349
2,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",51.2062,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.900,2098
3,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,56.9245,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.727,31025
4,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,109.4062,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,False,False,8.710,1831

In [107]:
df[['id',	'title',	'original_language','original_title','popularity','release_date','vote_average','vote_count']]

,id,title,original_language,original_title,popularity,release_date,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,122.7143,2026-07-24,9.259,848
1,1632181,Accidental Partners,es,Socias por accidente,24.9711,2026-03-12,8.905,349
2,1007757,Swapped,en,Swapped,51.2062,2026-05-01,8.900,2098
3,278,The Shawshank Redemption,en,The Shawshank Redemption,56.9245,1994-09-23,8.727,31025
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,109.4062,2025-07-18,8.710,1831
5,238,The Godfather,en,The Godfather,59.0628,1972-03-14,8.686,23342
6,936075,Michael,en,Michael,84.8355,2026-04-22,8.700,4003
7,687163,Project Hail Mary,en,Project Hail Mary,131.1924,2026-03-15,8.656,7038
8,240,The Godfather Part II,en,The Godfather Part II,31.3571,1974-12-20,8.571,14171
9,424,Schindler's List,en,Schindler's List,34.1502,1993-12-15,8.570,17735
10,389,12 Angry Men,en,12 Angry Men,27.3154,1957-04-10,8.568,10229
11,1232449,Young Hearts,nl,Young Hearts,18.1933,2024-10-26,8.567,304
12,155,The Dark Knight,en,The Dark Knight,62.3278,2008-07-16,8.534,36383
13,129,Spirited Away,ja,千と千尋の神隠し,35.3381,2001-07-20,8.534,18688
14,1218925,Chainsaw Man - The Movie: Reze Arc,ja,劇場版 チェンソーマン レゼ篇,34.5511,2025-09-19,8.525,1112
15,497,The Green Mile,en,The Green Mile,34.2412,1999-12-10,8.506,19603
16,19404,Dilwale Dulhania Le Jayenge,hi,दिलवाले दुल्हनिया ले जायेंगे,14.3904,1995-10-20,8.505,4612
17,122,The Lord of the Rings: The Return of the King,en,The Lord of the Rings: The Return of the King,50.4122,2003-12-17,8.504,27079
18,496243,Parasite,ko,기생충,37.1941,2019-05-30,8.490,21079
19,372058,Your Name.,ja,君の名は。,27.7150,2016-07-01,8.484,12842

In [108]:
df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg,"[16, 28, 12, 14]",980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",122.7143,/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg,2026-07-24,False,False,9.259,848
1,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,24.9711,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.905,349
2,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",51.2062,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.900,2098
3,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,56.9245,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.727,31025
4,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,109.4062,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,False,False,8.710,1831

In [109]:
df.shape

(20, 15)

In [110]:
data=pd.DataFrame()

In [113]:
import time

Final_data=pd.DataFrame()

# Make an initial request to get the total number of pages
initial_url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"
initial_headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlOWViOGJmNDZlNzdhMjVhZGY0YTAzZjkzMTM0MDRiYSIsIm5iZiI6MTc4Njc5MzQ1Ny4wNTMsInN1YiI6IjZhODA0ZGYxMDM1N2FiNTY1OTkzZjlmOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.WEJ-oAD2jw066P6gcSoNSf7aPpSOIuQZLrpFV__liN8"
}
initial_response = requests.get(url=initial_url, headers=initial_headers)
initial_json_data = initial_response.json()

total_pages = 1 # Default to 1 in case of error
if 'total_pages' in initial_json_data:
    total_pages = initial_json_data['total_pages']
    print(f"Total pages available: {total_pages}")
else:
    print(f"Warning: 'total_pages' not found in initial response. Defaulting to 1 page. Response: {initial_json_data}")

# Loop through the actual number of pages
for i in range(1, total_pages + 1):
  url=f"https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={i}"

  headers = {
      "accept": "application/json",
      "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlOWViOGJmNDZlNzdhMjVhZGY0YTAzZjkzMTM0MDRiYSIsIm5iZiI6MTc4Njc5MzQ1Ny4wNTMsInN1YiI6IjZhODA0ZGYxMDM1N2FiNTY1OTkzZjlmOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.WEJ-oAD2jw066P6gcSoNSf7aPpSOIuQZLrpFV__liN8"
  }

  try:
    response = requests.get(url=url, headers=headers)
    response.raise_for_status() # Raise an exception for bad status codes (4xx or 5xx)
    # Check if 'results' key exists before trying to access it
    if 'results' in response.json():
      df=pd.DataFrame(response.json()['results'])
      df=df[['id', 'title', 'original_language','original_title','popularity','release_date','vote_average','vote_count']]
      Final_data=pd.concat([Final_data,df],ignore_index=True) # Changed ignore_index to True for proper concatenation
    else:
      print(f"Warning: 'results' key not found in response for page {i}. Response: {response.json()}")
  except requests.exceptions.RequestException as e:
    print(f"Error fetching page {i}: {e}")

  time.sleep(0.1) # Add a small delay to avoid hitting rate limits

Total pages available: 556
Error fetching page 501: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=501
Error fetching page 502: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=502
Error fetching page 503: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=503
Error fetching page 504: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=504
Error fetching page 505: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=505
Error fetching page 506: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=506
Error fetching page 507: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=507
Error fetching page 508: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=508
Error fetching page 509: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=509
Error fetching page 510: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=510
Error fetching page 511: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=511
Error fetching page 512: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=512
Error fetching page 513: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=513
Error fetching page 514: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=514
Error fetching page 515: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=515
Error fetching page 516: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=516
Error fetching page 517: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=517
Error fetching page 518: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=518
Error fetching page 519: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=519
Error fetching page 520: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=520
Error fetching page 521: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=521
Error fetching page 522: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=522
Error fetching page 523: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=523
Error fetching page 524: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=524
Error fetching page 525: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=525
Error fetching page 526: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=526
Error fetching page 527: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=527
Error fetching page 528: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=528
Error fetching page 529: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=529
Error fetching page 530: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=530
Error fetching page 531: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=531
Error fetching page 532: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=532
Error fetching page 533: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=533
Error fetching page 534: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=534
Error fetching page 535: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=535
Error fetching page 536: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=536
Error fetching page 537: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=537
Error fetching page 538: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=538
Error fetching page 539: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=539
Error fetching page 540: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=540
Error fetching page 541: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=541
Error fetching page 542: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=542
Error fetching page 543: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=543
Error fetching page 544: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=544
Error fetching page 545: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=545
Error fetching page 546: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=546
Error fetching page 547: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=547
Error fetching page 548: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=548
Error fetching page 549: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=549
Error fetching page 550: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=550
Error fetching page 551: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=551
Error fetching page 552: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=552
Error fetching page 553: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=553
Error fetching page 554: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=554
Error fetching page 555: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=555
Error fetching page 556: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=556

In [114]:
Final_data.head()

,id,title,original_language,original_title,popularity,release_date,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,en,Avatar Aang: The Last Airbender,122.7143,2026-07-24,9.259,848
1,1632181,Accidental Partners,es,Socias por accidente,24.9711,2026-03-12,8.905,349
2,1007757,Swapped,en,Swapped,51.2062,2026-05-01,8.900,2098
3,278,The Shawshank Redemption,en,The Shawshank Redemption,56.9245,1994-09-23,8.727,31025
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,109.4062,2025-07-18,8.710,1831

In [115]:
Final_data.shape

(10000, 8)

In [117]:
Final_data.to_csv("Top_Rated_Movies.csv",index=False)

In [118]:
Final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   original_language  10000 non-null  object
 3   original_title     10000 non-null  object
 4   popularity         10000 non-null  float64
 5   release_date       10000 non-null  object
 6   vote_average       10000 non-null  float64
 7   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(4)
memory usage: 625.1+ KB

In [ ]:
from google.colab import drive
drive.mount('/content/drive')